<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE note [
    <!ELEMENT note ( to, from, heading, body)>
    <!ELEMENT to (#PCDATA)>
    <!ELEMENT from (#PCDATA)>
    <!ELEMENT heading (#PCDATA)>
    <!ELEMENT body (#PCDATA)>
]>
<note>
    <to>Tove</to>
    <from>Jani</from>
    <heading>Reminder</heading>
    <body> <![CDATA[<a> <a>]]>Don't forget me this weekend</body>
</note>

<!--
• &lt; standing for < 
• &gt; standing for > 
• &amp; standing for & 
• &apos; standing for ‘ apostrophe 
• &quot; standing for” quotation mark
-->
