<?xml version="1.0"?>
<!DOCTYPE bookstore [
  <!ELEMENT bookstore (shipping+, book+)>   <!-- shipping, book 최소 한 개 이상-->
  <!ELEMENT shipping (duration)>            <!-- <shipping>은 반드시 <duration> 하나를 자식으로 가짐. -->
  <!ATTLIST shipping shipID ID #REQUIRED>   <!--<!ATTLIST shipping shipID ID #REQUIRED> <shipping>에는 필수 속성 shipID가 있고 타입은 ID. 같은 문서에서 유일(unique) 해야 함. -->
  <!ELEMENT book (#PCDATA)>
  <!ATTLIST book
            shippedBy  IDREF  #IMPLIED>
  <!ELEMENT duration (#PCDATA)>
]>
<bookstore>
  <shipping shipID="S1">
    <duration>3-5 days</duration>
  </shipping>
  <shipping shipID="S2">
    <duration>7-10 days</duration>
  </shipping>

  <book shippedBy="S1">XML in a Nutshell</book>
  <book shippedBy="S2">Effective DTD</book>
  <book>Local Pickup Only</book> <!-- shippedBy는 선택 속성이라 없어도 OK -->
</bookstore>